### ISSUE TITLE
Change recommended local server

### ISSUE THREAD

**Issue by burkmarr** [burkmarr/tombiovis#1]
There is a much simpler, ready-made simple node.js simple local server implementation called 'http-server' that could be configured & recommended instead of the way we currently do it. Requires only one node.js package instead of two and requires less setup/configuration than the method we currently recommend.

**Comment by enpjp** [comment]
For Chrome users there is an even easier option: The Chrome Webserver App.

**Comment by burkmarr** [comment]
enpjp's idea to recommend the Chrome Webserver App rather than one based on Node.js has been adopted. It is much simpler to install and start. It does mean that we are recommending Chrome as a development browser for knowledge-base developers, but it does _not_ mean that users of visualisations need to use Chrome. The use of Chrome Webserver App is only a recommendation not a requirement.
