### ISSUE TITLE
Macros don't work with LibreOffice

### ISSUE THREAD

**Issue by colinl** [burkmarr/tombiovis#6]
Currently the macros in kb/biscuits/biscuits.xls don't work with LibreOffice. Has anyone done any work on macros that will work? I have got the Save as CSV one basically working but have not looked at the others yet. My plan was to put both versions in the macro with the LO code commented out so it could be enabled if required.

**Comment by burkmarr** [comment]
That sounds like an interesting and useful piece of work.

**Comment by colinl** [comment]
OK, I will press on with it. I am pushed for time at the moment though so it might take a little while. If anyone urgently needs the code to get the export to csv going ask here and I will post the code snippet.

**Comment by burkmarr** [comment]
After considering this, I don't want to go beyond supporting Excel in the core software, though macros for LibreOffice or any other would be welcome. Instead I would like to move more and more to a strategy where there is no reliance on any particular spreadsheet.
